version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # change if your code is in a subfolder
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
