name: Update README with Recent Activity

on:
  schedule:
    - cron: "0 * * * *" # Hourly
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JamesIves/github-activity-readme@v2.4.0
        with:
          COMMIT_MSG: "chore: update README with recent activity"
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
